const fs = require('fs');

const translations = {
  "ItemType History Configuration Report summarizes the Default History template, any Tracked Properties, and Lifecycles. If no History Template is assigned, the message &quot;This ItemType does not have a History Template defined.&quot; appears in a Tear-Off window.": "ItemType 历史配置报告汇总了默认历史模板、跟踪属性和生命周期。如果未分配历史模板，独立窗口中将显示「此 ItemType 未定义历史模板」消息。",
  "Enables you to use wildcards &apos;%&apos; and &apos;*&quot; in the search condition. Example: Using Part Number like BR* returns all Items with part": "允许您在搜索条件中使用通配符 '%' 和 '*'。示例：使用零部件编号包含 BR* 返回零部件编号以 BR 开头的所有项目。",
  "Inverts the search condition you specify and allows the use of wildcards &apos;%&apos; and &apos;*&quot; in the search condition. Example: Using Part": "反转您指定的搜索条件并允许在搜索条件中使用通配符 '%' 和 '*'。",
  "Enables you to search for properties that explicitly have a NULL value in the database. Example: Using Type null returns all Items for whom the Type (": "允许您搜索数据库中明确具有 NULL 值的属性。示例：使用 Type 为空 返回 Type 属性为空的所有项目。",
  "Enables you to search any properties that have a value that has been set. Example: Using Type not null returns all Items for whom Type (property has s": "允许您搜索已设置值的任何属性。示例：使用 Type 不为空 返回 Type 属性有值的所有项目。",
  "Each row is an AND condition for the search. There can be many rows in the advanced search filter. A scroll bar is available to move up and down the l": "每一行是搜索的一个 AND 条件。高级搜索过滤器中可以有多行。可以使用滚动条上下移动查看所有条件。",
  "For more information on AML, you can refer to the Programmer&apos;s Guide available in the Documentation section of the Aras web-site. You can also at": "有关 AML 的更多信息，您可以参考 Aras 网站文档部分的程序员指南。您也可以联系 Aras 获取更多信息。",
  "A Boolean; when set to true, the item in this state cannot be edited. Typically this property is set to true when the status of the state is Released.": "布尔值；设置为 true 时，此状态中的项目不能被编辑。通常在状态为已发布时将此属性设置为 true。",
  "For an example of state permissions, look at the default Part Life Cycle map. While a Part is in the Preliminary state All Employees can get and updat": "有关状态权限的示例，请查看默认零部件生命周期映射。当零部件处于初始状态时，所有员工可以获取和更新它。",
  "Click the button to the right of the History Template field. Select a History Template from the pop-up search dialog. See the help topic on Configurab": "点击历史模板字段右侧的按钮。从弹出的搜索对话框中选择一个历史模板。有关可配置网格，请参阅帮助主题。",
  "Select Add Transition from the popup menu. A transition is created from the specified state and connected to the mouse. Drag the mouse to the state wh": "从弹出菜单中选择「添加转换」。从指定状态创建一个转换并连接到鼠标。将鼠标拖到目标状态。",
  "When items (i.e. Inspection Results) are created, the user creating the Inspection Result will be given only the eligible choices in the Classificatio": "创建项目（即检查结果）时，创建检查结果的用户将只获得分类中的合格选择。",
  "Because a user may belong to multiple groups and have multiple classification rights, it&apos;s not possible to automatically select a classification ": "由于用户可能属于多个组并拥有多个分类权限，因此无法自动选择分类。",
  "Test the behavior by creating a new Item of that ItemType, and one by one selecting each leaf classification. The form should immediately switch after": "通过创建该 ItemType 的新项目并逐一选择每个叶子分类来测试行为。选择分类后表单应立即切换。",
  "In the Navigation pane, select Administration --&gt; Forms. Click the Search Forms button to search for the GeometricShape form.": "在导航窗格中，选择 管理 --&gt; 表单。点击「搜索表单」按钮搜索 GeometricShape 表单。",
  "In the Navigation pane, select Administration&gt;Forms&gt;Search Forms. Search for the GeometricShape form, and create a new instance.": "在导航窗格中，选择 管理&gt;表单&gt;搜索表单。搜索 GeometricShape 表单并创建新实例。",
  "Notice that the Color property is inherited by all subclasses, because it was defined at the GeometricShape parent level.": "注意，颜色属性被所有子类继承，因为它是在 GeometricShape 父级别定义的。",
  "The System populates the selected action records as new rows in the History Template Action relationship grid.": "系统将选定的操作记录作为新行填充到历史模板操作关系网格中。",
  "This History Template will now override the History Template specified in the ItemType definition for each item instance that is in this Life Cycle st": "此历史模板现在将覆盖此生命周期状态中每个项目实例的 ItemType 定义中指定的历史模板。",
  "Indicates the action that was performed on the item. See 'History Actions' (above) for the list of potential actions": "指示对项目执行的操作。有关可能的操作列表，请参阅「历史操作」（上文）。",
  "In the ItemType definition form, select a History Template by clicking the ellipses in the upper portion of the form (to the right of the History Temp": "在 ItemType 定义表单中，点击表单上部的省略号选择历史模板（在历史模板字段右侧）。",
  "Click the Select Items button on the relationship toolbar (note that Select Items is the only action available). The History Action search dialog appe": "点击关系工具栏上的「选择项目」按钮（注意选择项目是唯一可用的操作）。将出现历史操作搜索对话框。",
  "In the Navigation pane, select Administration&gt;ItemTypes&gt;Search ItemTypes. The Search grid appears.": "在导航窗格中，选择 管理&gt;ItemTypes&gt;搜索 ItemTypes。将出现搜索网格。",
  "Edit the History Template ItemType and add TOC Access for: Name = Administrators Category = Administration": "编辑历史模板 ItemType 并添加目录访问：名称 = 管理员，类别 = 管理",
  "In the Navigation pane, select Administration&gt; History Template&gt;Create New History Template. A blank History Template form appears.": "在导航窗格中，选择 管理&gt;历史模板&gt;创建新历史模板。将出现空白历史模板表单。",
  "A system generated comment based on what is defined in the 'History Template Action'. For example, if a property is changed, the comment may include t": "基于「历史模板操作」中定义的内容由系统生成的评论。例如，如果属性被更改，评论可能包括更改的属性名称和旧值/新值。",
  "If the selected History Template has 'Store Property History' set to true (checked), then any properties with the Track History attribute enabled will": "如果选定的历史模板的「存储属性历史」设置为 true（选中），则启用跟踪历史属性的任何属性将被记录在历史中。",
  "Select a History Template by clicking the in the upper portion of the form (to the right of the History Template field). The system will launch a sear": "点击表单上部的省略号选择历史模板（在历史模板字段右侧）。系统将启动搜索对话框。",
  "Figure 3 shows a &apos;null&apos; relationship, where there is no related item. This pattern is useful when there is a need to track Items (Values, Co": "图3显示了一个「空」关系，其中没有关联项目。此模式适用于需要跟踪仅属于源项目且不会被重用的项目（值、评论等）的情况。",
  "Figure 3 shows a &apos;null&apos; relationship, where there is no related item. This pattern is useful when there is a need to track Items (Values, Comments, etc.) that pertain only to the source Item and would not be reused.": "图3显示了一个「空」关系，其中没有关联项目。此模式适用于需要跟踪仅属于源项目且不会被重用的项目（值、评论等）的情况。",
  "NULL relationships are useful when you need to provide the ability for a user to add more than one piece of the same information to an Item, but do not need or don't have another ItemType to make a connection. In the example above, a NULL relationship is used to define the ability for a User to add multiple remarks to an Item. A &apos;remarks&apos; String property can be assigned to the Relationship Item. Each time a User defines a new remark an additional Relationship Item is created. No additional related item is necessary.": "当您需要为用户提供向项目添加多条相同信息的能力，但不需要或没有另一个 ItemType 来建立连接时，空关系非常有用。在上面的示例中，空关系用于定义用户向项目添加多条备注的能力。「备注」字符串属性可以分配给关系项目。每次用户定义新备注时，都会创建一个额外的关系项目。不需要额外的关联项目。",
  "Here is an instance of Test, called TestPart. Notice that its initial revision is PartA. Notice also that this item is in the Released life cycle state. This means that the next time we update and save the item, it should have not only a new generation, but also a new Major Rev or revision.": "这是 Test 的一个实例，名为 TestPart。注意其初始修订为 PartA。还要注意此项目处于已发布生命周期状态。这意味着下次我们更新并保存项目时，它不仅应该有一个新的世代号，还应该有一个新的主修订号。",
  "Let&apos;s edit and save the item again. Here is the result. Notice that the next element in the Revision series is used to increment Major Rev.": "让我们再次编辑并保存项目。以下是结果。注意修订序列中的下一个元素用于递增主修订号。",
  "A customer-defined sequence of States and Transitions between States that are used as a primary driver of business rules. All Items are defined to be in one State within one specified Lifecycle. The State names are not significant; flags on each State&apos;s definition determine the behaviors.": "客户定义的状态序列和状态之间的转换，用作业务规则的主要驱动因素。所有项目都定义在一个指定生命周期中的一个状态中。状态名称不重要；每个状态定义上的标志决定行为。",
  "A state within the Lifecycle that has been specifically designated as the starting point for the Lifecycle. When a new Item is created, its state is automatically set to the start state. When Versioning, the item will be set back to its lifecycle start state whenever its version (i.e. generation) changes.": "生命周期中被指定为起始点的状态。创建新项目时，其状态自动设置为起始状态。进行版本控制时，每当项目的版本（即世代号）更改时，项目将被重置为其生命周期起始状态。",
  "A state within the Lifecycle that has been specifically flagged as the release state. There may be more than one release state in a lifecycle. When an item in release state is versioned, its Major_Rev is incremented, it is set back to its lifecycle start state, and its generation is incremented.": "生命周期中被标记为发布状态的状态。一个生命周期中可以有多个发布状态。当处于发布状态的项目被版本化时，其主修订号递增，重置为生命周期起始状态，世代号递增。",
  "An action to change the State of an Item, by assigning it another State from the same Lifecycle that is connected by a Transition.": "通过分配同一生命周期中通过转换连接的另一个状态来更改项目状态的操作。",
  "A set of actions used to initiate and save changes to Items, which result in versioning when automatic versioning is selected. These actions affect the Generation value on versionable items. If an item is edited after being released, these actions also change the Major_Rev property. Behavior of the Minor_Rev property is controlled by custom logic implemented by each organization.": "用于启动和保存项目更改的一组操作，当选择自动版本控制时会导致版本化。这些操作影响可版本化项目上的世代号值。如果项目在发布后被编辑，这些操作还会更改主修订号属性。次修订号属性的行为由每个组织实现的自定义逻辑控制。",
  "In case where multiple edits are needed for an item with automatic versioning, the user may Claim the item to prevent multiple versions from being applied. While the item is claimed, the Generation will only increment once until the User decides to Unclaim it.": "对于需要多次编辑的自动版本化项目，用户可以认领项目以防止应用多个版本。项目被认领期间，世代号只会递增一次，直到用户决定取消认领。",
  "When an activity is activated, those identities that have been assigned to it, or assignees, are notified and the activities appear in their InBasket. The assignees then open what is known as the Activity Completion Worksheet, which guides them through the list of tasks to be completed as well as any other work that needs to be performed before the activity can be completed. Also, the assignees will have a chance to choose the exit path from the activity, or vote. Depending on this vote the next activity to be activated is chosen.": "当活动被激活时，分配给它的身份（即受让人）会收到通知，活动出现在其收件箱中。受让人随后打开活动完成工作表，该工作表引导他们完成任务列表以及在活动完成之前需要执行的任何其他工作。此外，受让人将有机会选择活动的退出路径或投票。根据此投票结果，将选择下一个要激活的活动。",
  "The third option is an existing forum owned by the user. Selecting this option would add the selected item to that Forum. It is not possible for a user to add an item to a Forum they do not own.": "第三个选项是用户拥有的现有论坛。选择此选项会将选定项目添加到该论坛中。用户无法将项目添加到他们不拥有的论坛中。",
  "If the above values are entered, then the ECN numbers would be as follows: ECN-x": "如果输入了上述值，则 ECN 编号将如下所示：ECN-x",
  "If the above values are entered, then the ECN numbers would be as follows: ECN-0": "如果输入了上述值，则 ECN 编号将如下所示：ECN-0",
  "If the user decides not to save the markup notations, then he can click on the V": "如果用户决定不保存批注标记，可以点击查看器工具栏中的退出批注模式按钮。",
  "Opens the Search window to search an Item and replaces the current related/child": "打开搜索窗口搜索项目，并替换当前关联/子项目。",
  "Opens the View Direction Selector:": "打开视图方向选择器：",
  "Opens the Display Style Selector:": "打开显示样式选择器：",
  "Promotes the Item to the next available state, defined in the assigned Lifecycle": "将项目提升到分配的生命周期中定义的下一个可用状态。",
  "Promotes the Relationship Item and NOT the child or related Item.": "提升的是关系项目，而非子项目或关联项目。",
  "4. Click OK to save the changes in the Share Forum dialog box or click Cancel to": "4. 点击确定保存共享论坛对话框中的更改，或点击取消退出。",
  "4. Click the Select Items icon . The Life Cycle Map search dialog appears. Click": "4. 点击「选择项目」图标。将出现生命周期映射搜索对话框。点击返回所选图标。",
  "Right click on the J-100002 row and click Versions in the context menu that appe": "右键点击 J-100002 行，然后在出现的上下文菜单中点击「版本」。",
  "Right click on the Item Type and select Properties. You will see a dialog that d": "右键点击 ItemType 并选择「属性」。您将看到一个显示该 ItemType 所有属性的对话框。",
  "Select an activity in the Workflow Map Editor which will be used to initiate the": "在工作流映射编辑器中选择一个活动，用于启动子流程。",
  "Open an ItemType in a Structure Browser. For detailed steps, refer to To open an": "在结构浏览器中打开 ItemType。有关详细步骤，请参阅在结构浏览器中打开 ItemType。",
  "Open an ItemType and select Structure Browser from the menu. For detailed steps,": "打开 ItemType 并从菜单中选择「结构浏览器」。有关详细步骤，请参阅在结构浏览器中打开 ItemType。",
  "Open an Item in the Structure Browser. For detailed steps, refer to To open an I": "在结构浏览器中打开项目。有关详细步骤，请参阅在结构浏览器中打开项目。",
  "Members of this identity decide whether or not proposed changes to a software pr": "此身份的成员决定是否批准对软件产品的拟议更改。",
  "Members of this Identity have control over various aspects of the workflow of PR": "此身份的成员控制 PR 工作流的各个方面。",
  "Members of this Identity have control over some aspects of the workflow of the E": "此身份的成员控制 ECR 工作流的某些方面。",
  "SharePoint User - the account that you have designated for this library connecti": "SharePoint 用户 - 您为此库连接指定的帐户",
  "SharePoint User Password - password for the user above": "SharePoint 用户密码 - 上述用户的密码",
  "SharePoint User Domain - SharePoint may require that the user's domain is provid": "SharePoint 用户域 - SharePoint 可能要求提供用户的域",
  "Indicates one or more files to be viewed with the 3D viewer .": "指示一个或多个要使用3D查看器查看的文件。",
  "Indicates one or more files to be viewed with the PDF viewer .": "指示一个或多个要使用 PDF 查看器查看的文件。",
  "Indicates one or more files to be viewed with the Image viewer .": "指示一个或多个要使用图像查看器查看的文件。",
  "Pick two points to create a measurement.": "选择两个点创建测量。",
  "Pick two planar faces to create an angular measurement.": "选择两个平面创建角度测量。",
  "Pick two planar faces to create an distance measurement.": "选择两个平面创建距离测量。",
  "BLUE – Indicates no Item found with matching structure.": "蓝色 - 表示未找到匹配结构的项目。",
  "Select an image for the button by clicking the Select an image link, selecting a": "通过点击「选择图像」链接、选择图像并确认来为按钮选择图像。",
  "Select an identity and click the Return Selected button to add it to the Replica": "选择一个身份并点击「返回所选」按钮将其添加到复制列表中。",
  "You can specify the values of the Item&apos;s properties you want to conduct the": "您可以指定要执行搜索的项目属性值。",
  "You can click Make New Folder to create new folders on the client machine.": "您可以点击「新建文件夹」在客户端机器上创建新文件夹。",
  "Find the Database for the Innovator to be updated. Please be certain that this i": "找到要更新的 Innovator 数据库。请确保这是正确的数据库。",
  "Find the Database for the Innovator to be updated.": "找到要更新的 Innovator 数据库。",
  "2. Click the New Email button to create your own email. A row is added to the di": "2. 点击「新建电子邮件」按钮创建自己的电子邮件。将向显示网格添加一行。",
  "2. Click the New Email button to create your own email.": "2. 点击「新建电子邮件」按钮创建自己的电子邮件。",
  "● ItemType Permissions Report summarizes all the Permissions showing who can get, update, delete and": "● ItemType 权限报告汇总了所有权限，显示谁可以获取、更新、删除和更改权限。",
  "Share...": "分享...",
  "Item inside a Forum": "论坛内的项目",
  "Saved Search inside a Forum": "论坛内的保存搜索",
  "Items (in Items group)": "项目（在项目组中）",
  "Follow": "关注",
  "Not Lockable": "不可锁定",
  "Item Behavior": "项目行为",
  "State Permissions": "状态权限",
  "Configure E-Mail": "配置电子邮件",
  "Workflow": "工作流",
  "History Template": "历史模板",
  "Creating a Transition": "创建转换",
  "Using Client Display Mode": "使用客户端显示模式",
  "Action": "操作",
  "Comment": "评论",
  "Item State": "项目状态",
  "Default History Template:": "默认历史模板：",
  "Category = Administration": "类别 = 管理",
  "Created_on_tick": "创建时间戳",
  "Creating a Configured email": "创建配置的电子邮件",
  "Using Variables in Email Text": "在电子邮件正文中使用变量",
  "Definition": "定义",
  "Body HTML": "HTML 正文",
  "Query String": "查询字符串",
  "On Activate": "激活时",
  "On Assign": "分配时",
  "On Refuse": "拒绝时",
  "On Delegate": "委派时",
  "On Vote": "投票时",
  "On Remind": "提醒时",
  "On Escalate": "升级时",
  "On Close": "关闭时",
  "Alternate": "替代",
  "Released": "已发布",
  "Vote on me": "对我投票",
  "Where Used": "使用位置",
  "Revisions": "修订",
  "Add to Package Definition": "添加到包定义",
  "Reset Lifecycle State": "重置生命周期状态",
  "Reset Item Access": "重置项目访问权限",
  "Set Default Life Cycle": "设置默认生命周期",
  "ItemType Definition Report": "ItemType 定义报告",
  "ItemType Permissions Report": "ItemType 权限报告",
  "Replace": "替换",
  "Open the selected item.": "打开选定项目。",
  "Copy the selected row.": "复制选定行。",
  "Paste the selected row.": "粘贴选定行。",
  "Reports -": "报告 -",
  "Name - the name of the map": "名称 - 映射名称",
  "State Property": "状态属性",
  "The name of the state": "状态名称",
  "To create a list:": "创建列表：",
  "Thumbnail Image Display": "缩略图显示",
  "Privileges": "特权",
  "Enables you to delete item": "允许您删除项目",
  "Can Discover": "可以发现",
  "Can Change Access": "可以更改访问权限",
  "Show Permission Warning": "显示权限警告",
  "TOC Access": "目录访问",
  "To enter a value for access:": "输入访问值：",
  "Creating a Sequence": "创建序列",
  "Using @mention": "使用 @提及",
  "New ItemType": "新建 ItemType",
  "Effectivity Type drop-down": "生效类型下拉框",
  "As of (date)": "截至（日期）",
  "Class Path": "类路径",
  "Tooltip": "工具提示",
  "Help Text": "帮助文本",
  "Track History": "跟踪历史",
  "Z-Index": "Z 轴顺序",
  "File Item": "文件项目",
  "Group Box": "分组框",
  "Selecting an Item": "选择项目",
  "In the Form, click .": "在表单中，点击。",
  "Inserts a button element": "插入按钮元素",
  "Inserts a calendar element": "插入日历元素",
  "Inserts a color element": "插入颜色元素",
  "Inserts an image element": "插入图像元素",
  "Forum Permissions": "论坛权限",
  "Navigate": "导航",
  "Hide Tabs in Tab View": "在选项卡视图中隐藏选项卡",
  "Displays the following menu:": "显示以下菜单：",
  "Reports": "报告",
  "Grouping Identities": "分组身份",
  "Downloads the file.": "下载文件。",
  "Prints the file.": "打印文件。",
  "Switch to Standard Toolbar": "切换到标准工具栏",
  "Execution in Progress": "执行进行中",
  "Completed Failed Canceled": "已完成 失败 已取消",
  "Execution Canceled": "执行已取消",
  "Completed Failed": "已完成 失败",
  "Execution Complete": "执行完成",
  "1159 Completed": "1159 已完成",
  "2 Failed": "2 失败",
  "Erasing a Message": "删除消息",
  "Automatic Messages": "自动消息",
  "Allow Private Permissions -": "允许私有权限 -",
  "Discussion Panel": "讨论面板",
  "Bookmarks Panel": "书签面板",
  "Creating a Permission": "创建权限",
  "Can Add Permission": "可添加权限",
  "Run Search": "执行搜索",
  "Executes the search.": "执行搜索。",
  "Clear Search Criteria": "清除搜索条件",
  "Search Mode drop-down": "搜索模式下拉框",
  "Enables tab redline view.": "启用选项卡红线视图。",
  "Use wildcards": "使用通配符",
  "Append results": "追加结果",
  "Sort across pages": "跨页排序",
  "Results per Page": "每页结果数",
  "Previous Page": "上一页",
  "Next Page": "下一页",
  "Show Total Pages and Results": "显示总页数和结果数",
  "Maximum Results": "最大结果数",
  "Save Search...": "保存搜索...",
  "Delete Saved Search": "删除保存的搜索",
  "To change Required to True:": "将「必填」更改为「是」：",
  "From TOC select ItemTypes.": "从目录中选择 ItemTypes。",
  "Save the file and close": "保存文件并关闭",
  "Open Enterprise Manager": "打开企业管理器",
  "Input the following query:": "输入以下查询：",
  "Where:": "条件：",
  "From the Windows Start Menu": "从 Windows 开始菜单",
  "Open Administrative Tools": "打开管理工具",
  "Open Services": "打开服务",
  "Select Restart": "选择重新启动",
  "To change Required to False:": "将「必填」更改为「否」：",
  "Library Selection": "库选择",
  "Test the Connection": "测试连接",
  "Active": "活动",
  "Inactive": "非活动",
  "Indication": "指示",
  "Searching for Dates": "搜索日期",
  "Authentication Admin": "认证管理员",
  "Authentication Administrators": "认证管理员组",
  "Authenticators": "认证器",
  "Change Control Board (CCB)": "变更控制委员会（CCB）",
  "Classification Administrators": "分类管理员",
  "Component Engineering": "零部件工程",
  "Conversion Manager": "转换管理员",
  "Manager": "管理员",
  "Process Planner Admin": "流程规划管理员",
  "QP Admin": "质量规划管理员",
  "Quality Planning": "质量规划",
  "Highlight": "高亮",
  "Style Name": "样式名称",
  ".title": "标题",
  "Title text": "标题文本",
  "Message text": "消息文本",
  ".notification_ok_btn": "通知确认按钮",
  "OK Button text": "确认按钮文本",
  ".notification_exit_btn": "通知退出按钮",
  "Exit Button text": "退出按钮文本",
  "Assignee": "受让人",
  "Voting Weight": "投票权重",
  "Required": "必填",
  "Displays the PDF file.": "显示 PDF 文件。",
  "Markup": "批注",
  "Deletes selected item.": "删除选定项目。",
  "Downloads a file.": "下载文件。",
  "Prints a file.": "打印文件。",
  "Switch to Basic Toolbar": "切换到基本工具栏",
  "Zoom Up": "放大",
  "Zooms closer": "放大查看",
  "Zoom Down": "缩小",
  "Zooms farther away": "缩小查看",
  "Reset View": "重置视图",
  "Resets to previous view.": "恢复为上一视图。",
  "Orient to Face": "朝向面",
  "Set Display Style": "设置显示样式",
  "Measure": "测量",
  "Exploded View": "爆炸视图",
  "Cross Section": "截面",
  "Model Browser": "模型浏览器",
  "Configurations": "配置",
  "Fit Width": "适合宽度",
  "Fit Height": "适合高度",
  "Page Up": "上一页",
  "Page Down": "下一页",
  "Go To Page": "跳转到页面",
  "This opens the Paging dialog:": "打开分页对话框：",
  "This opens the Find dialog:": "打开查找对话框：",
  "Zoom Percent": "缩放百分比",
  "This opens the Zoom dialog:": "打开缩放对话框：",
  "Rotate 90 CW": "顺时针旋转90度",
  "Rotate 90 CCW": "逆时针旋转90度",
  "Open Advanced": "展开高级工具",
  "Open the Advanced toolbar.": "展开高级工具栏。",
  "Close Advanced": "关闭高级工具",
  "Close the Advanced toolbar.": "关闭高级工具栏。",
  "Image viewer Toolbar": "图像查看器工具栏",
  "3D Viewer Toolbar": "3D 查看器工具栏",
  "Zoom closer": "放大",
  "Zoom farther away": "缩小",
  "Set View Direction": "设置视图方向",
  "Iso View": "等轴测视图",
  "Sets view to Iso View.": "设置为等轴测视图。",
  "Left View": "左视图",
  "Sets view to Left View.": "设置为左视图。",
  "Right View": "右视图",
  "Sets view to Right View.": "设置为右视图。",
  "Bottom View": "底视图",
  "Sets view to Bottom View.": "设置为底视图。",
  "Front View": "前视图",
  "Sets view to Front View.": "设置为前视图。",
  "Back View": "后视图",
  "Sets view to Back View.": "设置为后视图。",
  "Top View": "顶视图",
  "Sets view to Top View.": "设置为顶视图。",
  "Wireframe": "线框",
  "Display as Wireframe.": "以线框模式显示。",
  "Hidden Line": "隐藏线",
  "Display as Hidden Line.": "以隐藏线模式显示。",
  "Shaded": "着色",
  "Display as Shaded.": "以着色模式显示。",
  "Wireframe on Shaded": "着色线框",
  "Opens the Measure dialog:": "打开测量对话框：",
  "Measure Point to Point": "点到点测量",
  "Measure Edges": "边测量",
  "Measure Angle Between Faces": "面间角度测量",
  "Turn off measurement.": "关闭测量。",
  "Set Rotation Style": "设置旋转样式",
  "Set rotation style to Walk.": "设置旋转样式为步行。",
  "Turntable": "转盘",
  "Orbit Camera": "轨道相机",
  "LifeCycle": "生命周期",
  "Escalate To": "升级到",
  "Message": "消息",
  "Expected Duration": "预期持续时间",
  "Timeout Duration": "超时持续时间",
  "Reminder Interval": "提醒间隔",
  "Reminder Count": "提醒次数",
  "Subflow": "子流程",
  "Managed By": "管理人",
  "Start Activity": "起始活动",
  "End Activity": "结束活动",
  "Automatic Activity": "自动活动",
  "Can Refuse": "可以拒绝",
  "Can Delegate": "可以委派",
  "Consolidate Delegated": "合并委派",
  "Wait For All Inputs": "等待所有输入",
  "Wait For All Votes": "等待所有投票",
  "Activity Tabs": "活动选项卡",
  "Default Path Example": "默认路径示例",
  "Required Example": "必填示例",
  "Wait For All Votes Example": "等待所有投票示例",
  "Creator - Reject (10%)": "创建者 - 拒绝（10%）",
  "Log on to Aras Innovator.": "登录 Aras Innovator。",
  "Select Structure Browser.": "选择结构浏览器。"
};

// Read SQL
const sql = fs.readFileSync('INSERT_系统管理详解_full.sql', 'utf-8');

let replaced = 0;
const result = sql.replace(/<Run xml:lang="zh-cn">([^<]+)<\/Run>/g, (match, text) => {
  if (/[一-鿿]/.test(text)) return match;
  if (text.startsWith('分类:') || text.startsWith('来源:')) return match;
  if (text.length < 2) return match;

  const trimmed = text.trim();
  if (translations[trimmed] || translations[text]) {
    replaced++;
    return `<Run xml:lang="zh-cn">${translations[trimmed] || translations[text]}</Run>`;
  }
  return match;
});

fs.writeFileSync('INSERT_系统管理详解_full.sql', result);
console.log(`Replaced ${replaced} more paragraphs.`);

const remaining = [...result.matchAll(/<Run xml:lang="zh-cn">([^<]+)<\/Run>/g)]
  .filter(m => !/[一-鿿]/.test(m[1]) && m[1].length > 3 && !m[1].startsWith('分类') && !m[1].startsWith('来源'));
const uniqueRemaining = [...new Set(remaining.map(m => m[1]))];
console.log(`Remaining unique English: ${uniqueRemaining.length}`);
fs.writeFileSync('remaining_english4.json', JSON.stringify(uniqueRemaining, null, 2));
