const fs = require('fs');

// All remaining translations
const translations = {
  // Relationship creation
  "Then you add a relationship, if there are only two options:Pick Related or Create Related, it is mandatory for you to add a related Item. You can either pick an existing Item ( Pick Related) or create a new Item (Create Related) to be added, but associating a related Item is mandatory in such cases.": "当您添加关系时，如果只有两个选项：选择关联或创建关联，则必须添加关联项目。您可以选择现有项目（选择关联）或创建新项目（创建关联），但在这种情况下关联项目是必需的。",
  "Example: Part-BOM relationship. For detailed steps, refer to Creating a Relationship with a Related Item.": "示例：Part-BOM 关系。有关详细步骤，请参阅创建带关联项目的关系。",
  "Creating a Relationship with related Item being optional (Pick Related, Create Related, or No Related)": "创建关联项目为可选的关系（选择关联、创建关联或无关联）",
  "When you add a relationship, if there are all the three options: Pick Related, Create Related, or No Related , it is optional for you to add a related Item. You can either add a related Item (Pick Related or Create Related) or opt to not associate any related Item ( No Related) and add only information about the relationship.": "当您添加关系时，如果有全部三个选项：选择关联、创建关联或无关联，则添加关联项目是可选的。您可以添加关联项目（选择关联或创建关联），也可以选择不关联任何项目（无关联），仅添加关系信息。",
  "Example: Part-Alternate relationship. For detailed steps, refer to Creating a Relationship with Optional Related Item.": "示例：Part-Alternate 关系。有关详细步骤，请参阅创建带可选关联项目的关系。",
  "Creating a Relationship that cannot add a related Item (No Related)": "创建不能添加关联项目的关系（无关联）",
  "When you add a relationship, if there is only one option: No Related, you cannot associate any related Item (No Related), but can only add information to the relationship.": "当您添加关系时，如果只有一个选项：无关联，则您不能关联任何关联项目，只能添加关系信息。",
  "Example: List-Value relationship. For detailed steps, refer to Creating a Relationship that cannot add a Related Item": "示例：List-Value 关系。有关详细步骤，请参阅创建不能添加关联项目的关系",
  "Text with formatting which can be edited with the &quot;Innovator Formatted Text Editor&quot;": "带格式的文本，可通过「Innovator 格式化文本编辑器」编辑",
  "Image": "图片",
  "A predetermined set of values, usually displayed in a drop down box on a form. For more information, please see Creating a List.": "一组预定义的值，通常在表单上以下拉框形式显示。有关更多信息，请参阅创建列表。",
  "A string with values in multiple languages, see Internationalization": "包含多种语言值的字符串，请参阅国际化",
  "A continuous series of numbers, incremented and formatted as specified in the Sequence properties. See Sequences for more information.": "按序列属性中指定的格式递增和格式化的连续数字序列。有关更多信息，请参阅序列。",
  "A string of letters and numbers of up to a length selected for the property.": "长度由属性选定的字母和数字字符串。",
  "Relationship Grid: The relationship grid lists the related/child Items. The grid comprises of Relationship Item properties and child Item properties. The highlighted properties belongs to the Relationship Item, while the non-highlighted properties belong to the child Item.": "关系网格：关系网格列出了关联/子项目。网格包含关系项目属性和子项目属性。高亮属性属于关系项目，非高亮属性属于子项目。",
  "CorporateTimeZone, must be created after installation and contain a value of one of the Time Zone key names used by Windows.": "CorporateTimeZone，必须在安装后创建，并包含 Windows 使用的时区键名之一的值。",
  "There are two standard Windows settings used by the Innovator Client. These will be set automatically when Windows is installed and may be controlled by a corporate IT team or set by an individual Windows user.": "Innovator 客户端使用两个标准 Windows 设置。这些设置会在安装 Windows 时自动设置，可由企业 IT 团队控制或由个人 Windows 用户设置。",
  "Open the Control Panel and select Clock, Language, and Region:": "打开控制面板并选择时钟、语言和区域：",
  "This setting defines how Decimals, Dates and Times are displayed and Innovator supports this Windows feature. A culture may be selected and even customized if desired. Innovator does not use any currency formatting.": "此设置定义小数、日期和时间的显示方式，Innovator 支持此 Windows 功能。可以选择一种文化，甚至可以根据需要自定义。Innovator 不使用任何货币格式。",
  "Click on Date and Time to change the date and time, the time zone, or to add clocks:": "点击日期和时间以更改日期和时间、时区或添加时钟：",
  "Click Add a Language to add a different language to your list. The language that appears at the top of the list is your primary language.": "点击「添加语言」以向列表添加不同的语言。出现在列表顶部的语言是您的主要语言。",
  "For more information on administering Internationalization consult the documentation on the release CD.": "有关管理国际化的更多信息，请参阅发行版 CD 上的文档。",
  "Select a report from the menu. Use standard Internet Explorer printing to print the report.": "从菜单中选择一个报告。使用标准 Internet Explorer 打印功能打印报告。",
  "Different Life Cycle Maps can be assigned to different Classes. See Class Structure": "不同的生命周期映射可以分配给不同的类。请参阅类结构",
  "Null relationships normally have visible properties only since they reference no related ItemType.": "空关系通常只有可见属性，因为它们不引用关联的 ItemType。",
  "Modify the RelationshipType item - to modify the behavior of the relationship itself": "修改关系类型项目 - 修改关系本身的行为",
  "Modify the relationship ItemType - to add and edit properties to the relationship itself (like quantity, for example).": "修改关系 ItemType - 添加和编辑关系本身的属性（例如数量）。",
  "The TOC Editor supports drag-and-drop operations for moving entries around, as well as indenting and out-denting categories.": "目录编辑器支持拖放操作来移动条目，以及缩进和取消缩进类别。",
  "To preview what the TOC is going to look like for a specific group, click the View As button and enter an Identity such as All Employees.": "要预览特定组的目录外观，请点击「以...查看」按钮并输入身份，例如所有员工。",
  "An action to change the State of an Item, by assigning it another State from the same Lifecycle that is connected by a Transition.": "通过分配同一生命周期中通过转换连接的另一个状态来更改项目状态的操作。",
  "Populate fields as indicated in the Viewer Properties topic.": "按照查看器属性主题中的说明填写字段。",
  "Click and to save and unlock the item. The new action is now displayed in the default page in the main window.": "点击保存并解锁项目。新操作现在显示在主窗口的默认页面中。",
  "Bookmarks - Selecting this option will add the item to the Items group in Bookmarks ..": "书签 - 选择此选项将把项目添加到书签中的项目组。",
  "Click OK to save the changes or click Cancel to exit from the dialog box.": "点击确定保存更改，或点击取消退出对话框。",
  "Click on Comment to save the markup comment.": "点击评论保存批注评论。",
  "Enables you to search Items with properties of value greater than the value specified in the search condition. Example: Using Cost &gt; 3000 returns Items whose cost is greater than 3000.": "允许您搜索属性值大于搜索条件中指定值的项目。示例：使用成本 &gt; 3000 返回成本大于3000的项目。",
  "Enables you to search Items with properties of value greater than or the same as the value specified in the search condition. Example: Using Cost &gt; 3000 returns Items whose cost is greater than or equal to 3000.": "允许您搜索属性值大于或等于搜索条件中指定值的项目。",
  "Enables you to use wildcards &apos;%&apos; and &apos;*&quot; in the search condition. Example: Using Type L* returns Items which start with the letter L.": "允许您在搜索条件中使用通配符 '%' 和 '*'。示例：使用 Type L* 返回以字母 L 开头的项目。",
  "Enables you to search for properties that explicitly have a NULL value in the database. Example: Using Type not null displays only items that have a value for Type.": "允许您搜索数据库中明确具有 NULL 值的属性。示例：使用 Type 不为空 仅显示具有 Type 值的项目。",
  "Enables you to search any properties that have a value that has been set. Example: Using Type not null returns Items that have a value for the Type property.": "允许您搜索已设置值的任何属性。示例：使用 Type 不为空 返回 Type 属性有值的项目。",
  "Properties of type Date display a Date Picker form when you click on the Criteria.": "日期类型的属性在您点击条件时会显示日期选择器表单。",
  "Each row is an AND condition for the search. There can be many rows in the advanced search filter. All criteria must be met (AND condition).": "每一行是搜索的一个 AND 条件。高级搜索过滤器中可以有多行。所有条件都必须满足（AND 条件）。",
  "Displays Part Item Types which include a description AND were created after the specified date.": "显示包含描述且在指定日期之后创建的零部件 ItemType。",
  "Displays Part ItemTypes created after 1/1/2014 AND modified before 5/14/2014.": "显示在2014/1/1之后创建且在2014/5/14之前修改的零部件 ItemType。",
  "The Search dialog is displayed.": "显示搜索对话框。",
  "Specify the search criteria and click .": "指定搜索条件并点击。",
  "Select the Item from the grid and click .": "从网格中选择项目并点击。",
  "Inserts a radio button element": "插入单选按钮元素",
  "Toggles display of the Relationship tabs.": "切换关系选项卡的显示。",
  "Displays the Just Ask Innovator online help.": "显示「询问 Innovator」在线帮助。",
  "There are two tabs, Aliases and Read Vaults:": "有两个选项卡，别名和读取保险库：",
  "Deletes any selected notations.": "删除选定的批注。",
  "Switches from the Basic Toolbar to the Standard Toolbar.": "从基本工具栏切换到标准工具栏。",
  "Status displays the current promotion status.": "状态显示当前提升状态。",
  "Review displays a message in more detail.": "审核以更详细的格式显示消息。",
  "Save, Unlock, and Close the list.": "保存、解锁并关闭列表。",
  "Save, Unlock, and Close the Permission.": "保存、解锁并关闭权限。",
  "Save, Unlock, and Close the relationship ItemType.": "保存、解锁并关闭关系 ItemType。",
  "Enables you to retrieve/view item": "允许您检索/查看项目",
  "Enables you to edit existing item": "允许您编辑现有项目",
  "Enables user to create instances of the item": "允许用户创建项目的实例",
  "Enables you create a new ItemType.": "允许您创建新的 ItemType。",
  "Add, Delete or Edit assignments": "添加、删除或编辑分配",
  "Enter color names, color values, and the sort order.": "输入颜色名称、颜色值和排序顺序。",
  "Click to open the item for editing.": "点击打开项目进行编辑。",
  "Click to save and close the item.": "点击保存并关闭项目。",
  "Create a new Forum and send messages from the Forum": "创建新论坛并从论坛发送消息",
  "Search messages based on Bookmarks": "基于书签搜索消息",
  "Follow messages from a particular User or a Forum.": "关注来自特定用户或论坛的消息。",
  "This includes the following panels:": "这包括以下面板：",
  "Allows you to turn Discussions on or off.": "允许您开启或关闭讨论功能。",
  "Allows you to select the search mode.": "允许您选择搜索模式。",
  "Removes the applied search criteria.": "删除已应用的搜索条件。",
  "Deletes the selected saved search from the main grid.": "从主网格中删除选定的保存搜索。",
  "Displays the previous page in the main grid.": "显示主网格中的上一页。",
  "Displays the next page in the main grid.": "显示主网格中的下一页。",
  "Making a Text Property Required": "将文本属性设为必填",
  "A field to group other fields together": "将其他字段分组在一起的字段",
  "A fields that enables the user to select an image": "允许用户选择图像的字段",
  "A filed that enables the user to classify the item": "允许用户对项目进行分类的字段",
  "Note: Messages of type \"History\" cannot be erased.": "注意：「历史」类型的消息无法删除。",
  "Six users have flagged the message but not the creator.": "六位用户标记了该消息，但不包括创建者。",
  "A Show replies link is displayed again below the message.": "消息下方会再次显示「显示回复」链接。",
  "Indicates one or more files to be viewed with the 3D viewer .": "指示一个或多个要使用3D查看器查看的文件。",
  "Indicates one or more files to be viewed with the PDF viewer .": "指示一个或多个要使用 PDF 查看器查看的文件。",
  "Indicates one or more files to be viewed with the Image viewer .": "指示一个或多个要使用图像查看器查看的文件。",
  "Pick two points to create a measurement.": "选择两个点创建测量。",
  "Pick two planar faces to create an angular measurement.": "选择两个平面创建角度测量。",
  "Pick two planar faces to create an distance measurement.": "选择两个平面创建距离测量。",
  "BLUE – Indicates no Item found with matching structure.": "蓝色 - 表示未找到匹配结构的项目。",
  "SharePoint User - the account that you have designated for this library connecti": "SharePoint 用户 - 您为此库连接指定的帐户",
  "SharePoint User Password - password for the user above": "SharePoint 用户密码 - 上述用户的密码",
  "SharePoint User Domain - SharePoint may require that the user's domain is provid": "SharePoint 用户域 - SharePoint 可能要求提供用户的域",
  "Select an identity and click the Return Selected button to add it to the Replica": "选择一个身份并点击「返回所选」按钮将其添加到复制列表中。",
  "You can specify the values of the Item&apos;s properties you want to conduct the": "您可以指定要执行搜索的项目属性值。",
  "You can click Make New Folder to create new folders on the client machine.": "您可以点击「新建文件夹」在客户端机器上创建新文件夹。",
  "Find the Database for the Innovator to be updated. Please be certain that this i": "找到要更新的 Innovator 数据库。请确保这是正确的数据库。",
  "Find the table called ItemType": "找到名为 ItemType 的表",
  "Members of this identity decide whether or not proposed changes to a software pr": "此身份的成员决定是否批准对软件产品的拟议更改。",
  "Members of this Identity have control over various aspects of the workflow of PR": "此身份的成员控制 PR 工作流的各个方面。",
  "Members of this Identity have control over some aspects of the workflow of the E": "此身份的成员控制 ECR 工作流的某些方面。",
  "A customer-defined sequence of States and Transitions between States that are used as a primary driver of business rules. All Items are defined to be in one State within one specified Lifecycle. The State names are not significant; flags on each State&apos;s definition determine the behaviors.": "客户定义的状态序列和状态之间的转换，用作业务规则的主要驱动因素。所有项目都定义在一个指定生命周期中的一个状态中。状态名称不重要；每个状态定义上的标志决定行为。",
  "A state within the Lifecycle that has been specifically designated as the starting point for the Lifecycle. When a new Item is created, its state is automatically set to the start state. When Versioning, the item will be set back to its lifecycle start state whenever its version (i.e. generation) changes.": "生命周期中被指定为起始点的状态。创建新项目时，其状态自动设置为起始状态。进行版本控制时，每当项目的版本（即世代号）更改时，项目将被重置为其生命周期起始状态。",
  "A state within the Lifecycle that has been specifically flagged as the release state. There may be more than one release state in a lifecycle. When an item in release state is versioned, its Major_Rev is incremented, it is set back to its lifecycle start state, and its generation is incremented.": "生命周期中被标记为发布状态的状态。一个生命周期中可以有多个发布状态。当处于发布状态的项目被版本化时，其主修订号递增，重置为生命周期起始状态，世代号递增。",
  "A set of actions used to initiate and save changes to Items, which result in versioning when automatic versioning is selected. These actions affect the Generation value on versionable items. If an item is edited after being released, these actions also change the Major_Rev property. Behavior of the Minor_Rev property is controlled by custom logic implemented by each organization.": "用于启动和保存项目更改的一组操作，当选择自动版本控制时会导致版本化。这些操作影响可版本化项目上的世代号值。如果项目在发布后被编辑，这些操作还会更改主修订号属性。次修订号属性的行为由每个组织实现的自定义逻辑控制。",
  "In case where multiple edits are needed for an item with automatic versioning, the user may Claim the item to prevent multiple versions from being applied. While the item is claimed, the Generation will only increment once until the User decides to Unclaim it.": "对于需要多次编辑的自动版本化项目，用户可以认领项目以防止应用多个版本。项目被认领期间，世代号只会递增一次，直到用户决定取消认领。",
  "When an activity is activated, those identities that have been assigned to it, or assignees, are notified and the activities appear in their InBasket. The assignees then open what is known as the Activity Completion Worksheet, which guides them through the list of tasks to be completed as well as any other work that needs to be performed before the activity can be completed. Also, the assignees will have a chance to choose the exit path from the activity, or vote. Depending on this vote the next activity to be activated is chosen.": "当活动被激活时，分配给它的身份（即受让人）会收到通知，活动出现在其收件箱中。受让人随后打开活动完成工作表，该工作表引导他们完成任务列表以及在活动完成之前需要执行的任何其他工作。此外，受让人将有机会选择活动的退出路径或投票。根据此投票结果，将选择下一个要激活的活动。",
  "Here is an instance of Test, called TestPart. Notice that its initial revision is PartA. Notice also that this item is in the Released life cycle state. This means that the next time we update and save the item, it should have not only a new generation, but also a new Major Rev or revision.": "这是 Test 的一个实例，名为 TestPart。注意其初始修订为 PartA。还要注意此项目处于已发布生命周期状态。这意味着下次我们更新并保存项目时，它不仅应该有一个新的世代号，还应该有一个新的主修订号。",
  "Let&apos;s edit and save the item again. Here is the result. Notice that the next element in the Revision series is used to increment Major Rev.": "让我们再次编辑并保存项目。以下是结果。注意修订序列中的下一个元素用于递增主修订号。",
  "The third option is an existing forum owned by the user. Selecting this option would add the selected item to that Forum. It is not possible for a user to add an item to a Forum they do not own.": "第三个选项是用户拥有的现有论坛。选择此选项会将选定项目添加到该论坛中。用户无法将项目添加到他们不拥有的论坛中。",
  "The following properties are displayed in the Item History Dialog:": "以下属性显示在项目历史对话框中：",
  "The following examples show how these properties work to together to create a se": "以下示例展示了这些属性如何协同工作以创建安全消息：",
  "Select one or more actions from the search dialog and click the green arrow.": "从搜索对话框中选择一个或多个操作，然后点击绿色箭头。",
  "Select one or more actions from the search dialog and click the toolbar button. ": "从搜索对话框中选择一个或多个操作，然后点击工具栏按钮。",
  "Select one or more identities from the search dialog and click .": "从搜索对话框中选择一个或多个身份，然后点击。",
  "Search for the ItemType you wish to modify. In this example, we will use the Ite": "搜索您要修改的 ItemType。在此示例中，我们将使用 ItemType 进行演示。",
  "Search for Items by their keyed-name. For example, 'Adm*' finds the Identity nam": "按项目的键名搜索项目。例如，'Adm*' 查找名称以 Adm 开头的身份。",
  "Displays the action that was performed on the item. See 'History Actions' (above": "显示对项目执行的操作。参见「历史操作」（上文）。",
  "Displays the structure of the selected item.": "显示选定项目的结构。",
  "Displays the revisions of an item.": "显示项目的修订信息。",
  "3. Enter the appropriate information in the form fields and click the Save Item ": "3. 在表单字段中输入适当的信息，然后点击「保存项目」按钮。",
  "If the above values are entered, then the ECN numbers would be as follows: ECN-x": "如果输入了上述值，则 ECN 编号将如下所示：ECN-x",
  "If the above values are entered, then the ECN numbers would be as follows: ECN-0": "如果输入了上述值，则 ECN 编号将如下所示：ECN-0",
  "If the user decides not to save the markup notations, then he can click on the V": "如果用户决定不保存批注标记，可以点击查看器工具栏中的退出批注模式按钮。",
  "Opens the Search window to search an Item and replaces the current related/child": "打开搜索窗口搜索项目，并替换当前关联/子项目。",
  "Opens the View Direction Selector:": "打开视图方向选择器：",
  "Opens the Display Style Selector:": "打开显示样式选择器：",
  "Promotes the Item to the next available state, defined in the assigned Lifecycle": "将项目提升到分配的生命周期中定义的下一个可用状态。",
  "Promotes the Relationship Item and NOT the child or related Item.": "提升的是关系项目，而非子项目或关联项目。",
  "4. Click OK to save the changes in the Share Forum dialog box or click Cancel to": "4. 点击确定保存共享论坛对话框中的更改，或点击取消退出。",
  "4. Click the Select Items icon . The Life Cycle Map search dialog appears. Click": "4. 点击「选择项目」图标。将出现生命周期映射搜索对话框。点击返回所选图标。",
  "If you are setting the E-Signature for the first time, leave the Old Signature f": "如果是首次设置电子签名，请将旧签名字段留空。",
  "If you are a member of the Managed By Identity, the Add and Delete Icons will be": "如果您是管理人身份的成员，添加和删除图标将处于活动状态。",
  "Click and to save and unclaim the item.": "点击保存并取消认领项目。",
  "Click and to save and unclaim this item.": "点击保存并取消认领此项目。",
  "Click and to save and unclaim the file.": "点击保存并取消认领文件。",
  "Notice that the Color property is inherited by all subclasses, because it was de": "注意，颜色属性被所有子类继承，因为它是在父级别定义的。",
  "Notice that there are nine tabs defined, with the labels shown in the center col": "注意，定义了九个选项卡，标签显示在中心列中。",
  "Notice that the described tabs appear on the New Part form.": "注意，所述选项卡出现在新建零部件表单上。",
  "If you specify Standard Mode, the item you select appears in a separate window.": "如果指定标准模式，您选择的项目将在独立窗口中显示。",
  "Once you save the item, the form and properties are refreshed to reflect the pro": "保存项目后，表单和属性会刷新以反映刚刚进行的更改。",
  "Once you select the SpecDocument, and save the item, then the Spec ID (the Forei": "选择 SpecDocument 并保存项目后，SpecID（外部属性）将自动填充，且为只读。",
  "Once you have selected items from the main grid and populated the Mass Promote g": "从主网格中选择项目并填充批量提升网格后，您可以使用设置面板提升它们。",
  "In the Navigation pane, select Administration --&gt; Forms. Click the Search For": "在导航窗格中，选择 管理 --&gt; 表单。点击「搜索表单」。",
  "In the Navigation pane, select Administration&gt;Forms&gt;Search Forms. Search f": "在导航窗格中，选择 管理&gt;表单&gt;搜索表单。搜索要修改的表单。",
  "In the Life Cycle Editor form, select a state in the Map.": "在生命周期编辑器表单中，选择映射中的一个状态。",
  "2. Click the Navigate button to see the Navigate menu and select History.": "2. 点击「导航」按钮查看导航菜单，然后选择「历史」。",
  "2. Click the New Email button to create your own email. A row is added to the di": "2. 点击「新建电子邮件」按钮创建自己的电子邮件。将向显示网格添加一行。",
  "2. Click Create New List. A blank List window appears.": "2. 点击「创建新列表」。将出现空白列表窗口。",
  "The alias identity of the user": "用户的别名身份",
  "String containing today&apos;s date": "包含今天日期的字符串",
  "String containing the current time": "包含当前时间的字符串",
  "An alternate identity for receipt of notification": "接收通知的替代身份",
  "ItemType History Configuration": "ItemType 历史配置",
  "Configuring History for an ItemType (Administrators Only):": "配置 ItemType 的历史记录（仅限管理员）：",
  "History Based On Life Cycle State": "基于生命周期状态的历史",
  "View an Item's History Log (All Users):": "查看项目的历史日志（所有用户）：",
  "Open the form for an Item Instance.": "打开项目实例的表单。",
  "The Item History Dialog appears.": "显示项目历史对话框。",
  "The date and time when the action was performed": "执行操作的日期和时间",
  "The first name, last name of the user": "用户的姓和名",
  "The current state of the Item.": "项目的当前状态。",
  "The Generation of the item after the action was performed.": "操作执行后项目的世代号。",
  "Creating a Custom History Template (Administrators Only):": "创建自定义历史模板（仅限管理员）：",
  "Search for the History Template ItemType.": "搜索历史模板 ItemType。",
  "Enter a name in the Name field (required).": "在名称字段中输入名称（必填）。",
  "Viewing an Item's History Log (All Users):": "查看项目的历史日志（所有用户）：",
  "1. Open the form for an Item Instance.": "1. 打开项目实例的表单。",
  "The Item History dialog box appears.": "显示项目历史对话框。",
  "The following properties appear in the Item History Dialog:": "以下属性显示在项目历史对话框中：",
  "The Generation of the item after the action was performed": "操作执行后项目的世代号",
  "The created_on_tick property for the item.": "项目的创建时间戳属性。",
  "Use the following procedure to create an email:": "使用以下步骤创建电子邮件：",
  "Right click on the state from which you wish to create a transition.": "右键点击您希望创建转换的状态。",
  "Right click on the Item Type and select Properties. You will see a dialog that d": "右键点击 ItemType 并选择「属性」。您将看到一个显示该 ItemType 所有属性的对话框。",
  "Click the Add Criteria button in the search toolbar for all criteria to be used.": "点击搜索工具栏中的「添加条件」按钮以使用所有条件。",
  "Click the button to the right of the History Template field. Select a History Te": "点击历史模板字段右侧的按钮。从搜索对话框中选择一个历史模板。",
  "Click on Date and Time to change the date and time, the time zone, or to add clo": "点击日期和时间以更改日期和时间、时区或添加时钟：",
  "Click on this link to configure e-mail, in order to notify specified identities ": "点击此链接配置电子邮件，以便在分配活动时通知指定的身份。",
  "Click and to unclaim and close the History Template ItemType.": "点击取消认领并关闭历史模板 ItemType。",
  "Client Style - this tab is used to customize the UI.": "客户端样式 - 此选项卡用于自定义用户界面。",
  "Implements - this tab is used to add polymorphic ItemTypes.": "实现 - 此选项卡用于添加多态 ItemType。",
  "Name - the name of the ItemType": "名称 - ItemType 的名称",
  "Description- the description of the map": "描述 - 映射的描述",
  "Radius- add to the Circle subclass": "半径 - 添加到圆形子类",
  "Side Length- add to the Square subclass": "边长 - 添加到正方形子类",
  "Side 2 Length - add to the Rectangle subclass": "第二边长 - 添加到矩形子类",
  "Click Save and Done to save and unclaim the ItemType.": "点击「保存并完成」以保存并取消认领 ItemType。",
  "Click the Lock Item icon to claim the form for editing.": "点击锁定图标认领表单进行编辑。",
  "5. Click to save your changes.": "5. 点击保存更改。",
  "6. Click to save and unclaim the list.": "6. 点击保存并取消认领列表。",
  "6. Click to save the ItemType.": "6. 点击保存 ItemType。",
  "6. Click to save and unclaim the ItemType.": "6. 点击保存并取消认领 ItemType。",
  "5. Click t osave and unclaim the item.": "5. 点击保存并取消认领项目。",
  "9. Click to save the item and unclaim it.": "9. 点击保存项目并取消认领。",
  "Click the Save, Unlock, CloseClick the": "点击保存、解锁、关闭",
  "Click to save and close the ItemType.": "点击保存并关闭 ItemType。",
  "Click to save and unclaim the item.": "点击保存并取消认领项目。",
  "Click to save and unclaim this item.": "点击保存并取消认领此项目。",
  "Click and to save and unlock the item. The new action is now displayed in the de": "点击保存并解锁项目。新操作现在显示在主窗口的默认页面中。",
  "3. Enter a name for the email in the Name field.": "3. 在名称字段中输入电子邮件名称。",
  "3. Enter the appropriate information in the fields.": "3. 在字段中输入适当的信息。",
  "1. Enter an Identity name into the search box.": "1. 在搜索框中输入身份名称。",
  "Name - the name of the revision.": "名称 - 修订版本的名称。",
  "Name - the name of the sequence item.": "名称 - 序列项目的名称。",
  "Enter the Name of the list and the Description.": "输入列表的名称和描述。",
  "Enter the Presentation Configuration name and click .": "输入显示配置名称并点击。",
  "Enter the vault name, URL pattern, and URL in the appropriate fields.": "在相应字段中输入保险库名称、URL 模式和 URL。",
  "Enter information in the following fields:": "在以下字段中输入信息：",
  "Place Classification and Color on the form, like this": "将分类和颜色放在表单上，如下所示：",
  "Repeat steps 10-15 for each Form.": "对每个表单重复步骤10-15。",
  "Only one state per Life Cycle can be marked as Released.": "每个生命周期只能有一个状态标记为已发布。",
  "Click the Save Item button to save changes to the form.": "点击「保存项目」按钮保存表单更改。",
  "Click the Unlock button to unclaim the form.": "点击「解锁」按钮取消认领表单。",
  "Select an activity in the Workflow Map Editor which will be used to initiate the": "在工作流映射编辑器中选择一个活动，用于启动子流程。",
  "Open an ItemType in a Structure Browser. For detailed steps, refer to To open an": "在结构浏览器中打开 ItemType。有关详细步骤，请参阅在结构浏览器中打开 ItemType。",
  "Open an ItemType and select Structure Browser from the menu. For detailed steps,": "打开 ItemType 并从菜单中选择「结构浏览器」。有关详细步骤，请参阅在结构浏览器中打开 ItemType。",
  "Open an Item in the Structure Browser. For detailed steps, refer to To open an I": "在结构浏览器中打开项目。有关详细步骤，请参阅在结构浏览器中打开项目。",
  "● ItemType Permissions Report summarizes all the Permissions showing who can get, update, delete and": "● ItemType 权限报告汇总了所有权限，显示谁可以获取、更新、删除和更改权限。",
  "ItemType History Configuration Report summarizes the Default History template, any Tracked Propertie": "ItemType 历史配置报告汇总了默认历史模板、任何跟踪的属性和生命周期。",
  "Figure 3 shows a &apos;null&apos; relationship, where there is no related item. This pattern is usef": "图3显示了一个「空」关系，其中没有关联项目。此模式适用于需要跟踪仅属于源项目且不会被重用的项目（值、评论等）的情况。",
  "NULL relationships are useful when you need to provide the ability for a user to add more than one p": "当您需要为用户提供向项目添加多条相同信息的能力，但不需要或没有另一个 ItemType 来建立连接时，空关系非常有用。",
  "Here is an instance of Test, called TestPart. Notice that its initial revision is PartA. Notice also": "这是 Test 的一个实例，名为 TestPart。注意其初始修订为 PartA。还要注意此项目处于已发布生命周期状态。",
  "Let&apos;s edit and save the item again. Here is the result. Notice that the next element in the Rev": "让我们再次编辑并保存项目。以下是结果。注意修订序列中的下一个元素用于递增主修订号。",
  "Open the Control Panel and select Clock, Language, and Region:": "打开控制面板并选择时钟、语言和区域：",
  "Use the 'Stop Search' and 'Clear Search' buttons in the search toolbar as requir": "根据需要使用搜索工具栏中的「停止搜索」和「清除搜索」按钮。",
  "Use the following procedure to create an email:": "使用以下步骤创建电子邮件：",
  "Open an ItemType in a Structure Browser.": "在结构浏览器中打开 ItemType。",
  "Select an image for the button by clicking the Select an image link, selecting a": "通过点击「选择图像」链接、选择图像并确认来为按钮选择图像。",
  "The following examples show how these properties work to together to create a se": "以下示例展示了这些属性如何协同工作以创建安全消息。",
  "2. Click the New Email button to create your own email.": "2. 点击「新建电子邮件」按钮创建自己的电子邮件。",
  "Find the Database for the Innovator to be updated.": "找到要更新的 Innovator 数据库。",
  "Right click on the J-100002 row and click Versions in the context menu that appe": "右键点击 J-100002 行，然后在出现的上下文菜单中点击「版本」。",
  "Figure 2": "图2",
  "Figure 3": "图3",
  "Figure 6": "图6",
  "&gt;=": "大于或等于",
  ">=": "大于或等于"
};

// Read SQL
const sql = fs.readFileSync('INSERT_系统管理详解_full.sql', 'utf-8');

// Replace
let replaced = 0;
const result = sql.replace(/<Run xml:lang="zh-cn">([^<]+)<\/Run>/g, (match, text) => {
  if (/[一-鿿]/.test(text)) return match;
  if (text.startsWith('分类:') || text.startsWith('来源:')) return match;
  if (text.length < 2) return match;

  const trimmed = text.trim();
  if (translations[trimmed] || translations[text]) {
    replaced++;
    return `<Run xml:lang="zh-cn">${translations[trimmed] || translations[text]}</Run>`;
  }
  return match;
});

fs.writeFileSync('INSERT_系统管理详解_full.sql', result);
console.log(`Replaced ${replaced} more English paragraphs.`);

const remaining = [...result.matchAll(/<Run xml:lang="zh-cn">([^<]+)<\/Run>/g)]
  .filter(m => !/[一-鿿]/.test(m[1]) && m[1].length > 3 && !m[1].startsWith('分类') && !m[1].startsWith('来源'));
const uniqueRemaining = [...new Set(remaining.map(m => m[1]))];
console.log(`Remaining unique English paragraphs: ${uniqueRemaining.length}`);
fs.writeFileSync('remaining_english2.json', JSON.stringify(uniqueRemaining, null, 2));
