<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/ArasToolkit.Services/ArasToolkit.Services.csproj" />
    <Reference Include="IOM">
      <HintPath>../../src/R37lib/IOM.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
